### ISSUE TITLE
[feature request] add setting to disable notification

### ISSUE THREAD

**Issue by nschoenwald** [misthero/last-scene-view#1]
Love the module, but I don't need the notification when the scene view is restored. Would love to have an option to turn it off.

**Comment by misthero** [comment]
> Love the module, but I don't need the notification when the scene view is restored. Would love to have an option to turn it off.

ok will do

**Comment by misthero** [comment]
for now you can use my other tiny module

https://github.com/misthero/warning-remove

you can configure it ro remove any message 😊

**Comment by misthero** [comment]
the setting to disable the message has been added
